name: Deploy Serverless S3 Scanner

# Manual trigger for deployment
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: false
        default: 'dev'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Setup Node.js for CDK
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install CDK
      run: npm install -g aws-cdk@latest

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Install Python dependencies
      run: |
        cd infrastructure
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Lambda dependencies
      run: |
        cd lambda
        pip install -r requirements.txt --target .

    - name: CDK Bootstrap
      run: |
        cd infrastructure
        cdk bootstrap

    - name: CDK Deploy
      run: |
        cd infrastructure
        cdk deploy --require-approval never --outputs-file outputs.json

    - name: Display deployment outputs
      run: |
        cd infrastructure
        echo "Deployment completed successfully!"
        echo "Check outputs.json for resource details"
        cat outputs.json